### ISSUE TITLE
optlink 8.00.17 crash at EIP=0040F60A

### ISSUE THREAD

**Issue by wilzbach** [wilzbach/tools-test#168]
Note: the issue was created automatically migrated from https://issues.dlang.org

Original bug ID: BZ#17508
From: Martin Nowak &lt;<code@dawg.eu>&gt;
Reported version: D2
CC:   computermatronic@gmail.com

**Comment by wilzbach** [comment]
Comment author: Martin Nowak &lt;<code@dawg.eu>&gt;

Happens with debug builds of scod v0.3.1.

https://github.com/MartinNowak/scod/issues/4

---------------------------
Unexpected OPTLINK Termination at EIP=0040F60A
---------------------------
EAX=051E0000 EBX=00438C70 ECX=0000048D EDX=0000033D 
ESI=00006400 EDI=051E2DCC EBP=0019FF38 ESP=0019FEF0 
First=00402000
---------------------------

**Comment by wilzbach** [comment]
Comment author: Computermatronic &lt;<computermatronic@gmail.com>&gt;

Also happens when trying to build seemingly any dub project dependent on vibe.d 0.8.2

**Comment by veelo** [comment]
Is there a way to force ddox / scod to be linked with a different linker? Using `--arch` as in `dub build -b ddox --arch=x86_mscoff` for building the documentation of a library has no effect on building the ddox application, it is still linked using `optlink`.

Maybe `dub` can be changed to avoid optlink on Windows for ddox builds?

(Edit: s/x86/x86_mscoff/)

**Comment by wilzbach** [comment]
Please post on the respective issue at Bugzilla. This was just a failed experiment at migrating from Bugzilla to GitHub issues.
